spring:
  profiles:
    active: dev
  data:
    rest:
      base-path: /api/data-rest
  security:
    oauth2:
      client:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  #    show-sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB
#  mvc:
#    static-path-pattern: "/files/**"
  web:
    resources:
      static-locations: classpath:/files/,classpath:/static/, file:${app.files-path}
      cache:
        cachecontrol:
          max-age: 30
          s-max-age: 50

app:
  web:
    image:
      url: http://localhost:${server.port}
      user-avatar-path: /user_avatar # 与 mvc.static-path-pattern 对应
  page-config:
    default-page-num: 0
    default-page-size: 20
    max-page-size: 100

games:
  ffo:
    users-vote-second: 30

