spring:
  profiles:
    active: dev
  data:
    rest:
      base-path: /api/data-rest
  security:
    oauth2:
      client:

app:
  init:
    poem-files-path: C:\\data\\github-project\\chinese-poetry\\json


